In [2]:
import numpy as np
import dolfin as dl

In [3]:
A1=np.array([[2,1],[0,4]])
A2=np.array([[3,1],[4,2]])
A3=np.kron(A1,A2)
print(A3)
print(type(A3))

[[ 6  2  3  1]
 [ 8  4  4  2]
 [ 0  0 12  4]
 [ 0  0 16  8]]
<class 'numpy.ndarray'>


In [4]:
vec1=np.array([1,2,3,4])
vec2=np.array([0,1,0,3])
V=np.kron(vec1,vec2)
print(V)

[ 0  1  0  3  0  2  0  6  0  3  0  9  0  4  0 12]


In [7]:
print(np.array([np.arange(5)]))

[[0 1 2 3 4]]
